Repository jenkinsci/sshd-plugin, pull requests merged in 2022-04, with the labels that each got.

#57 Remove some deprecated API calls
  src/main/java/org/jenkinsci/main/modules/sshd/AsynchronousCommand.java
  src/main/java/org/jenkinsci/main/modules/sshd/CLICommandAdapter.java
  src/main/java/org/jenkinsci/main/modules/sshd/PortAdvertiser.java
  src/main/java/org/jenkinsci/main/modules/sshd/UserAuthNamedFactory.java
  src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/CLITest.java
  src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImplTest.java
Labels: chore

#65 feat: enable continuous delivery workflow
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yaml
  .github/workflows/changelog.yml
  .mvn/maven.config
  pom.xml
Labels: enhancement

#68 Stop bundling SLF4J
  pom.xml
Labels: bug

#71 Use Eclipse Temurin for action, not AdoptOpenJDK
  .github/workflows/cd.yaml
Labels: dependencies
