Repository jenkinsci/sshd-plugin, pull requests merged in 2024-06, with the labels that each got.

#170 replace eddsa dependency with eddsa-api plugin
  pom.xml
Labels: dependencies, developer

#172 Move ssh keys to security user page when available
  src/main/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImpl.java
Labels: enhancement

#173 Adapt tests to categorised user properties
  src/test/java/org/jenkinsci/main/modules/cli/auth/ssh/UserPropertyImplTest.java
Labels: tests, developer
